services:

  frontend:
    image: bernobin/basicapp2-frontend:${APP_VERSION}
    ports:
      - "8080:80"
    depends_on:
      - backend
    restart: unless-stopped

  backend:
    image: bernobin/basicapp2-backend:${APP_VERSION}
    secrets:
      - db_user_password
    depends_on:
      db:
        condition: service_healthy
      # migrate:
      #   condition: service_completed_successfully
    restart: unless-stopped

  migrate:
    image: bernobin/basicapp2-backend:${APP_VERSION}
    command: ["python", "migrate.py"]
    secrets:
      - db_user_password
    depends_on:
      db: 
        condition: service_healthy


  db:
    image: mysql:8.4
    volumes:
      - mysql_data:/var/lib/mysql
      # - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db_root_password
      MYSQL_DATABASE: helloapp
      MYSQL_USER: hello
      MYSQL_PASSWORD_FILE: /run/secrets/db_user_password
    secrets:
      - db_root_password
      - db_user_password
    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-h",
          "localhost"
        ]
      interval: 5s
      timeout: 6s
      retries: 5
    restart: unless-stopped

secrets:
  db_root_password:
    file: ./secrets/db_root_password.txt
  db_user_password:
    file: ./secrets/db_user_password.txt

volumes:
  mysql_data:
